// <auto-generated />
using System;
using MentorBooking.Repository.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentorBooking.Repository.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241023092324_addForeignKey")]
    partial class addForeignKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentorBooking.Repository.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.GroupFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackId")
                        .HasName("PK__GroupFee__6A4BEDD632E261D8");

                    b.HasIndex("GroupId");

                    b.HasIndex("MentorId");

                    b.HasIndex(new[] { "FeedbackId" }, "UQ__GroupFee__6A4BEDD718225B07")
                        .IsUnique();

                    b.HasIndex(new[] { "SessionId" }, "UQ__GroupFee__C9F49291EC2DA840")
                        .IsUnique();

                    b.ToTable("GroupFeedback", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Mentor", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("ExperienceYears")
                        .HasColumnType("tinyint");

                    b.Property<string>("MentorDescription")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MentorId")
                        .HasName("PK__Mentors__053B7E9843339A2F");

                    b.HasIndex(new[] { "MentorId" }, "UQ__Mentors__053B7E99380E4BF5")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "UQ__Mentors__1788CC4DCD90DE59")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorFeedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackId")
                        .HasName("PK__MentorFe__6A4BEDD6FFDF27E8");

                    b.HasIndex("MentorId");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "FeedbackId" }, "UQ__MentorFe__6A4BEDD7EEDD57E4")
                        .IsUnique();

                    b.ToTable("MentorFeedback", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorSupportSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("PointsPerSession")
                        .HasColumnType("smallint");

                    b.Property<byte>("SessionCount")
                        .HasColumnType("tinyint");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.HasKey("SessionId")
                        .HasName("PK__MentorSu__C9F49290519072FB");

                    b.HasIndex("GroupId");

                    b.HasIndex("MentorId");

                    b.HasIndex(new[] { "SessionId" }, "UQ__MentorSu__C9F492915AA054B2")
                        .IsUnique();

                    b.ToTable("MentorSupportSessions");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorWorkSchedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte>("UnavailableDate")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleId")
                        .HasName("PK__MentorWo__9C8A5B492399C41F");

                    b.HasIndex("SessionId");

                    b.HasIndex(new[] { "ScheduleId" }, "UQ__MentorWo__9C8A5B482E1FDBDE")
                        .IsUnique();

                    b.ToTable("MentorWorkSchedules");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.PointTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("PointsChanged")
                        .HasColumnType("int");

                    b.Property<bool>("TransactionType")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TransactionId")
                        .HasName("PK__PointTra__55433A6BA0518C5D");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "TransactionId" }, "UQ__PointTra__55433A6A1AC580D8")
                        .IsUnique();

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.ProjectGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Topic")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("GroupId")
                        .HasName("PK__ProjectG__149AF36A6F7109E5");

                    b.HasIndex(new[] { "GroupId" }, "UQ__ProjectG__149AF36BA39FD5B0")
                        .IsUnique();

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skills__DFA09187CCE92901");

                    b.HasIndex(new[] { "SkillId" }, "UQ__Skills__DFA09186BDE3ACF2")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__32C52B99CFB61B90");

                    b.HasIndex(new[] { "UserId" }, "UQ__Students__1788CC4DA0F925B6")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "UQ__Students__32C52B9835FD26AF")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.StudentGroup", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("StudentId", "GroupId")
                        .HasName("PK__StudentG__838C84AFBF71794B");

                    b.HasIndex("GroupId");

                    b.HasIndex(new[] { "StudentId" }, "UQ__StudentG__32C52B98B6ACEFB9")
                        .IsUnique();

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.StudentsPaymentSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PaidAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PointsChanged")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "StudentId")
                        .HasName("PK__Students__4AD8C029A16F13A9");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "SessionId" }, "UQ__Students__C9F492919764073E")
                        .IsUnique();

                    b.ToTable("StudentsPaymentSession", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.UserPoint", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PointsBalance")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__UserPoin__1788CC4C8920074C");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserPoin__1788CC4D6F73A679")
                        .IsUnique();

                    b.ToTable("UserPoints");
                });

            modelBuilder.Entity("MentorSkill", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("MentorId", "SkillId")
                        .HasName("PK__MentorSk__68C17780A4D1C4A1");

                    b.HasIndex("SkillId");

                    b.ToTable("MentorSkills", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.GroupFeedback", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ProjectGroup", "Group")
                        .WithMany("GroupFeedbacks")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupFeed__Group__7FEAFD3E");

                    b.HasOne("MentorBooking.Repository.Models.Mentor", "Mentor")
                        .WithMany("GroupFeedbacks")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupFeed__Mento__00DF2177");

                    b.HasOne("MentorBooking.Repository.Models.MentorSupportSession", "Session")
                        .WithOne("GroupFeedback")
                        .HasForeignKey("MentorBooking.Repository.Models.GroupFeedback", "SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupFeed__Sessi__01D345B0");

                    b.Navigation("Group");

                    b.Navigation("Mentor");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Mentor", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("MentorBooking.Repository.Models.Mentor", "MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorFeedback", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.Mentor", "Mentor")
                        .WithMany("MentorFeedbacks")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorFee__Mento__7D0E9093");

                    b.HasOne("MentorBooking.Repository.Models.MentorSupportSession", "Session")
                        .WithMany("MentorFeedbacks")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorFee__Sessi__7E02B4CC");

                    b.HasOne("MentorBooking.Repository.Models.Student", "Student")
                        .WithMany("MentorFeedbacks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorFee__Stude__7EF6D905");

                    b.Navigation("Mentor");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorSupportSession", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ProjectGroup", "Group")
                        .WithMany("MentorSupportSessions")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorSup__Group__7849DB76");

                    b.HasOne("MentorBooking.Repository.Models.Mentor", "Mentor")
                        .WithMany("MentorSupportSessions")
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorSup__Mento__793DFFAF");

                    b.Navigation("Group");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorWorkSchedule", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.MentorSupportSession", "Session")
                        .WithMany("MentorWorkSchedules")
                        .HasForeignKey("SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorWor__Sessi__7A3223E8");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.PointTransaction", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.UserPoint", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PointTran__UserI__70A8B9AE");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Student", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", "User")
                        .WithOne("Student")
                        .HasForeignKey("MentorBooking.Repository.Models.Student", "StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.StudentGroup", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ProjectGroup", "Group")
                        .WithMany("StudentGroups")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentGr__Group__73852659");

                    b.HasOne("MentorBooking.Repository.Models.Student", "Student")
                        .WithOne("StudentGroup")
                        .HasForeignKey("MentorBooking.Repository.Models.StudentGroup", "StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentGr__Stude__72910220");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.StudentsPaymentSession", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.MentorSupportSession", "Session")
                        .WithOne("StudentsPaymentSession")
                        .HasForeignKey("MentorBooking.Repository.Models.StudentsPaymentSession", "SessionId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsP__Sessi__7B264821");

                    b.HasOne("MentorBooking.Repository.Models.Student", "Student")
                        .WithMany("StudentsPaymentSessions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentsP__Stude__7C1A6C5A");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.UserPoint", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", "User")
                        .WithOne("UserPoint")
                        .HasForeignKey("MentorBooking.Repository.Models.UserPoint", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MentorSkill", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorSki__Mento__76619304");

                    b.HasOne("MentorBooking.Repository.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK__MentorSki__Skill__7755B73D");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MentorBooking.Repository.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.ApplicationUser", b =>
                {
                    b.Navigation("Mentor")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();

                    b.Navigation("UserPoint")
                        .IsRequired();
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Mentor", b =>
                {
                    b.Navigation("GroupFeedbacks");

                    b.Navigation("MentorFeedbacks");

                    b.Navigation("MentorSupportSessions");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.MentorSupportSession", b =>
                {
                    b.Navigation("GroupFeedback");

                    b.Navigation("MentorFeedbacks");

                    b.Navigation("MentorWorkSchedules");

                    b.Navigation("StudentsPaymentSession");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.ProjectGroup", b =>
                {
                    b.Navigation("GroupFeedbacks");

                    b.Navigation("MentorSupportSessions");

                    b.Navigation("StudentGroups");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.Student", b =>
                {
                    b.Navigation("MentorFeedbacks");

                    b.Navigation("StudentGroup");

                    b.Navigation("StudentsPaymentSessions");
                });

            modelBuilder.Entity("MentorBooking.Repository.Models.UserPoint", b =>
                {
                    b.Navigation("PointTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
